HotelMangementSystem/Controllers/SecurityController.cs
using HotelMangementSystem.Models;
using HotelMangementSystem.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace HotelMangementSystem.Controllers
{
    public class SecurityController : Controller
    {
        private HotelDBEntities objHotelDBEntities;
        public SecurityController()
        {
            objHotelDBEntities = new HotelDBEntities();
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(EmployeeViewModel objEmployeeViewModel)
        {
            var bilgiler = objHotelDBEntities.Employee.FirstOrDefault(model => model.EmployeeUserName == objEmployeeViewModel.EmployeeUserName && model.EmployeePassword == objEmployeeViewModel.EmployeePassword);
            if(bilgiler != null)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.EmployeeUserName, false);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

HotelMangementSystem/Views/Security/Login.cshtml
@model HotelMangementSystem.ViewModel.EmployeeViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/Login_v1/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v1/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v1/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v1/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v1/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v1/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v1/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Login_v1/css/main.css">
    <!--===============================================================================================-->
</head>
<body>

    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="~/Login_v1/images/img-01.png" alt="IMG">
                </div>

                    @using (Html.BeginForm("Login", "Security", FormMethod.Post))
                    {
                        <h2>Otel Yönetim Sistemi</h2>
                    <span class="login100-form-title">
                        Personel Giriş
                    </span>

                    <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
                        <input class="input100" type="text" name="EmployeeUserName" placeholder="Kullanıcı Adı">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Password is required">
                        <input class="input100" type="password" name="EmployeePassword" placeholder="Şifre">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn">
                            Giriş
                        </button>
                    </div>

                    }


              
            </div>
        </div>
    </div>




    <!--===============================================================================================-->
    <script src="~/Login_v1/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v1/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Login_v1/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v1/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v1/vendor/tilt/tilt.jquery.min.js"></script>
    <script>
		$('.js-tilt').tilt({
			scale: 1.1
		})
    </script>
    <!--===============================================================================================-->
    <script src="j~/Login_v1/s/main.js"></script>

</body>
</html>